{
    "name": "Thinksoft No Create",
    "version": "19.0.1.2",
    "description": "Thinksoft No Create blocks creation of customers, products, etc... on built-in fields.",
    "summary": "Thinksoft No Create For Built-in Fields",
    "author": "Thinksoft Inc.",
    "license": "AGPL-3",
    "category": "Addons Custom/Thinksoft",
    "depends": ["sale", "account", "stock", "purchase", "crm", "mrp"],
    "data": [
        "views/account_move_views.xml",
        "views/crm_lead_views.xml",
        "views/mrp_bom_views.xml",
        "views/mrp_production_views.xml",
        "views/mrp_routing_workcenter_views.xml",
        "views/purchase_order_views.xml",
        "views/sale_order_views.xml",
        "views/stock_picking_views.xml",
    ],
    "auto_install": False,
    "application": False,
}
