{
    "name": "Thinksoft Reports",
    "summary": "All reports live here.",
    "description": """
        This module contains the custom report overrides of standard Odoo reports.
    """,
    "author": "Thinksoft Inc.",
    "website": "http://www.thinksoft.ca",
    "license": "AGPL-3",
    "category": "Addons Custom/Thinksoft",
    "version": "19.0.0.0.1",
    "depends": ["base"],
    "data": [
        "reports/reports_paperformats.xml",
        "reports/report_quotation.xml",
        "reports/certificate_of_compliance_templates.xml",
        "reports/commercial_invoice_templates.xml",
        "reports/coo_templates.xml",
        "reports/manufacture_copy_templates.xml",
        "reports/order_confirmation_templates.xml",
        "reports/oxygen_clean_certificate_templates.xml",
        "reports/receiving_list_templates.xml",
        "reports/quality_control_trailer_templates.xml",
        "reports/invoice_report_templates.xml",
        "reports/packing_slip_templates.xml",
        "reports/packing_slip_with_price_templates.xml",
        "reports/pick_list_templates.xml",
        "reports/payment_remittance_templates.xml",
        "reports/ir_actions_report.xml",
        "reports/report_purchase_order.xml",
        "reports/waybill_templates.xml",
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
}
